version: '3.4'

services:
  todoappfront:
    container_name: frontend
    restart: unless-stopped
    image: frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200 
    networks:
      - shared-network-back-front
    depends_on:
      - todoappback

  todoappback:
    container_name: backend
    restart: unless-stopped
    image: backend
    build:
      context: ./ToDoAppBack
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    depends_on:
      - ms-sql-server
    ports:
      - 800:800
    networks:
      - shared-network-back-front

  ms-sql-server:
    container_name: database
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1421:1421
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Bazepodataka123!"
      MSSQL_PID: "Express"
    networks:
      - shared-network-back-front


   

networks:
  shared-network-back-front:
